# Generated by Django 4.1.4 on 2023-01-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_model',
            field=models.CharField(max_length=100),
        ),
    ]
