# Generated by Django 4.1.4 on 2023-01-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_alter_devices_device_id_alter_devices_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(verbose_name='device id'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_model',
            field=models.CharField(max_length=100, verbose_name='device name'),
        ),
    ]
