# Generated by Django 4.1.4 on 2023-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0003_alter_devices_device_id_alter_devices_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_model',
            field=models.CharField(max_length=100, verbose_name='device model'),
        ),
    ]
