# Generated by Django 4.1.4 on 2023-01-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0004_alter_devices_device_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenshots.devices')),
            ],
            options={
                'verbose_name': 'screenshot',
                'verbose_name_plural': 'screenshots',
                'db_table': 'screenshot',
            },
        ),
    ]
