# Generated by Django 4.1.4 on 2023-01-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0005_screenshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'devices', 'verbose_name_plural': 'device'},
        ),
        migrations.AlterModelOptions(
            name='screenshots',
            options={'verbose_name': 'screenshots', 'verbose_name_plural': 'screenshot'},
        ),
    ]
