# Generated by Django 4.1.4 on 2023-01-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0006_alter_devices_options_alter_screenshots_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='screenshots',
            options={'verbose_name': 'screenshot', 'verbose_name_plural': 'screenshots'},
        ),
    ]
