# Generated by Django 4.1.4 on 2023-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0007_alter_devices_options_alter_screenshots_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_id',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_code',
            field=models.IntegerField(null=True, verbose_name='device code'),
        ),
    ]
