# Generated by Django 4.1.4 on 2023-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0008_remove_devices_device_id_devices_device_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_code',
            field=models.CharField(max_length=100, null=True, verbose_name='device code'),
        ),
    ]
