# Generated by Django 4.1.4 on 2023-01-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0014_alter_screenshots_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshots',
            name='device',
        ),
    ]
