# Generated by Django 4.1.4 on 2023-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0018_alter_screenshots_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='screenshot'),
        ),
    ]
