# Generated by Django 4.1.4 on 2023-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0019_alter_screenshots_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_code',
        ),
        migrations.AddField(
            model_name='devices',
            name='d_brand',
            field=models.CharField(max_length=100, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='devices',
            name='d_model',
            field=models.CharField(max_length=100, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='devices',
            name='d_serial',
            field=models.CharField(max_length=100, null=True, verbose_name='serial number'),
        ),
    ]
