# Generated by Django 4.1.5 on 2023-01-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0021_screenshots_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='d_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='d_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='d_serial',
            new_name='serial',
        ),
        migrations.RemoveField(
            model_name='screenshots',
            name='time',
        ),
    ]
