# Generated by Django 4.1.5 on 2023-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0022_rename_d_brand_devices_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create at'),
        ),
        migrations.AddField(
            model_name='devices',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last modify'),
        ),
        migrations.AddField(
            model_name='screenshots',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='screenshots',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last modify'),
        ),
    ]
