# Generated by Django 4.1.5 on 2023-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0023_devices_create_time_devices_modified_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
