# Generated by Django 4.1.5 on 2023-01-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0024_devices_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='is_active',
            new_name='is_active_phone',
        ),
    ]
