# Generated by Django 4.1.5 on 2023-01-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0025_rename_is_active_devices_is_active_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='screenshot'),
        ),
    ]
