# Generated by Django 4.1.5 on 2023-01-17 10:44

from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0037_alter_screenshots_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='is_active_phone',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='model',
            field=models.CharField(max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modify'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='serial',
            field=models.CharField(max_length=100, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='image',
            field=thumbnails.fields.ImageField(upload_to='screenshots/', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modify'),
        ),
    ]
