# Generated by Django 4.1.4 on 2022-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='avatar'),
        ),
    ]
