# Generated by Django 4.1.4 on 2023-01-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='phone_id',
        ),
        migrations.AddField(
            model_name='devices',
            name='d_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='d_id'),
        ),
        migrations.AddField(
            model_name='devices',
            name='d_name',
            field=models.CharField(max_length=100, null=True, verbose_name='d_name'),
        ),
        migrations.CreateModel(
            name='DevicesScreenShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True, verbose_name='s_id')),
                ('screenShot', models.ImageField(upload_to='', verbose_name='image')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.devices')),
            ],
        ),
    ]
