# Generated by Django 4.1.4 on 2023-01-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_screenshot_devicesscreenshots_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesscreenshots',
            name='s_id',
        ),
        migrations.AddField(
            model_name='devicesscreenshots',
            name='time',
            field=models.TimeField(null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='devicesscreenshots',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
