# Generated by Django 4.1.4 on 2023-01-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_devicesscreenshots_s_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesscreenshots',
            name='d_id',
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.DeleteModel(
            name='DevicesScreenShots',
        ),
    ]
