# Generated by Django 4.1.4 on 2023-01-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_devicesscreenshots_d_id_delete_devices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usersss', 'verbose_name_plural': 'user'},
        ),
    ]
