# Generated by Django 4.1.4 on 2023-01-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
