# Generated by Django 4.1.5 on 2023-01-17 08:39

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=thumbnails.fields.ImageField(max_length=200, null=True, upload_to='', verbose_name='avatar'),
        ),
    ]
